"""Combine every product's screenshot previews into one deployable WebP sprite.

The source index and individual previews are generated by build-tianzhao-previews.py.
Keep those individual files under .local-data/tianzhao-previews after generation;
only the one-file-per-product sprites belong in the deployed public directory.
One sprite per product keeps every screenshot browsable while reducing the public
asset count enough for the site's deployment provider.
"""

from __future__ import annotations

import json
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
SOURCE_INDEX = ROOT / "src/data/tianzhao-image-index.json"
SOURCE_DIR = ROOT / ".local-data/tianzhao-previews"
OUTPUT_DIR = ROOT / "public/tianzhao-sprites"
OUTPUT_INDEX = ROOT / "src/data/tianzhao-sprite-index.json"


def main() -> None:
    source = json.loads(SOURCE_INDEX.read_text(encoding="utf-8"))
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    products: dict[str, list[dict[str, object]]] = {}
    total_images = 0
    for product_id, items in source["products"].items():
        if not items:
            raise ValueError(f"No preview images for {product_id}")
        first_path = SOURCE_DIR / items[0]["url"].removeprefix("/tianzhao-previews/")
        destination = OUTPUT_DIR / f"{first_path.parent.name}.webp"
        images: list[Image.Image] = []
        for item in items:
            path = SOURCE_DIR / item["url"].removeprefix("/tianzhao-previews/")
            with Image.open(path) as opened:
                images.append(opened.convert("RGB"))
        width = max(image.width for image in images)
        total_height = sum(image.height for image in images)
        sprite = Image.new("RGB", (width, total_height), "white")
        entries: list[dict[str, object]] = []
        top = 0
        for item, image in zip(items, images, strict=True):
            sprite.paste(image, (0, top))
            entries.append({
                "url": f"/tianzhao-sprites/{destination.name}",
                "name": item["name"],
                "kind": item["kind"],
                "top": top,
                "height": image.height,
                "width": width,
                "totalHeight": total_height,
            })
            top += image.height
            image.close()
        sprite.save(destination, format="WEBP", quality=67, method=4)
        sprite.close()
        products[product_id] = entries
        total_images += len(entries)

    if len(products) != source["counts"]["productsWithPreviews"] or total_images != source["counts"]["previews"]:
        raise ValueError("Sprite coverage differs from the verified preview index")
    manifest = {
        "version": 1,
        "counts": {"products": len(products), "images": total_images},
        "products": products,
    }
    OUTPUT_INDEX.write_text(json.dumps(manifest, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    files = list(OUTPUT_DIR.glob("*.webp"))
    if len(files) != len(products):
        raise ValueError("Sprite file count differs from product count")
    print(json.dumps({"products": len(products), "images": total_images, "files": len(files), "bytes": sum(file.stat().st_size for file in files)}))


if __name__ == "__main__":
    main()
